### ISSUE TITLE
"AttributeError: module 'zenoh' has no attribute 'open'"

### ISSUE THREAD

**Issue by kkhao** [gabrik/zenoh-iftdt-demo#1]
When I run  ''run-cuda.sh'',  I got the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidData("AttributeError: module 'zenoh' has no attribute 'open'")', runtime/src/main.rs:91:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
./run-cuda.sh: line 3:  3056 Aborted
```

I have changed different versions of eclipse-zenoh, but still no work.

**Comment by gabrik** [comment]
Hi, @kkhao are you using the master version of `zenoh-python`? 
The demo is supposed to work with that version.

**Comment by kkhao** [comment]
I installed via pip install eclipse-zenoh, then version is 0.5.0b9.

**Comment by kkhao** [comment]
@gabrik Could you tell me the version you are using? Thanks.

**Comment by gabrik** [comment]
You should use the version from master: https://github.com/eclipse-zenoh/zenoh-python/ so please follow this instructions:

```
$ git clone https://github.com/eclipse-zenoh/zenoh-python/
$ cd zenoh-python
$ pip install -r requirements-dev.txt
$ python3 setup.py bdist_wheel
$ pip3 install ./dist/*.whl
```

**Comment by kkhao** [comment]
@gabrik  Thank you very much, I have solved the above problem, but now I have encountered a new problem. When recog.py is initialized, the following error occurred:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidData("AttributeError: module 'sys' has no attribute 'argv'")', runtime/src/main.rs:91:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
./run-cuda.sh: line 3:  3391 Aborted
 ```

I found that this error occurs when importing tensorflow, but I don't know what happened.
